### ISSUE TITLE
john dont pirate video games

### ISSUE THREAD

**Issue by HausemasterIssue** [John200410/RusherHackCrack#9]
you watched that anti-piracy ad and now your pirating your own game! thats illegal!

**Comment by ProfKambing** [comment]
😐

**Comment by ferderplays** [comment]
BRUH john200410 made Rusherhack so he pirated **his own work**

**Comment by acaiberii** [comment]
its not a crack

**Comment by ferderplays** [comment]
idiot i was just jokin
